language: java

jobs:
  include:
    - stage: deploy
      name: GitHub Release
      script:
        - ant distribute
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "$GITHUB_USER"
        - git config --local user.email "$GITHUB_MAIL"
        - export TRAVIS_TAG="v2.0.7-alpha"
        - git tag -f $TRAVIS_TAG
#        - git push origin :$TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        overwrite: true
        override: true
        file: 
          - magellan_v2.0.7.jar
          - magellan_v2.0.7.zip
        skip_cleanup: true
