language: java

jobs:
  include:
    - state: build
      name: Calling Ant to create distribution
      script: ant distribute
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "$GITHUB_USER"
        - git config --local user.email "$GITHUB_MAIL"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: 
          - magellan_v2.0.6.jar
          - magellan_v2.0.6.zip
        skip_cleanup: true
        on:
          tags: true