name: Create pre-release

on:
  push:
    branches:
      - "build-release"

jobs:
  build:
    name: Create pre-release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Test with ant
      run: |
         ant -noinput -buildfile build.xml run_tests
         fails=$(grep -L  "Failures: 0, Errors: 0" test/junit/TEST-*)
         if [ -n "$fails" ]; then
           echo Errors in $fails
           cat $fails
           exit 1
         fi
      # do not exit before all commands are executed
      shell: bash --noprofile --norc -o pipefail {0}
      
    - name: Build with ant
      run: ant -noinput -buildfile build.xml

    - name: Generate version string
      id: get-version
      run: |
        VERSION=$(ant -q -S print_version)
        echo "::set-env name=BASE::${VERSION}"
        echo "::set-env name=VERSION::${VERSION}-latest"
        echo "::set-env name=TAG::v${VERSION}-latest"

    - name: Read RELEASENOTES and CHANGELOG
      id: changelog
      run: |
        value=$(cat RELEASENOTES.txt | iconv -f ISO-8859-1; echo -e '\n# Excerpt from CHANGELOG.txt\n\n'; head -20 CHANGELOG.txt | iconv -f ISO-8859-1; echo -e '\n...\n' )
        value="${value//'%'/'%25'}"
        value="${value//$'\n'/'%0A'}"
        value="${value//$'\r'/'%0D'}"
        echo "::set-env name=BODY::$value"


