name: Create pre-release
# Test, build, and publish a release and tag it with "version-latest" on pushes to master

on:
  push:
    branches:
      - "build-release"

jobs:
  build:
    name: Create pre-release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Generate version string
      id: get-version
      run: |
        VERSION=$(ant -q -S print_version)
        SHORT=$(echo "${VERSION}" | cut -d. -f-2)
        BUILD=$(cat .build.number | grep build.number | cut -f2 -d"=")
        echo "::set-env name=BUILD::$BUILD"
        echo "::set-env name=SHORT::$SHORT"
        echo "::set-env name=VERSION::$VERSION"
        echo "::set-env name=TAG::$(echo "v${SHORT}-latest")"

    - name: Sanity check
      run: |
        if [[ "${TAG}" =~ ^v[0-9][0-9]*[.][0-9][0-9]*-latest$ ]]; then
          echo tag $TAG okay
        else
          echo "tag (${VERSION}, ${SHORT}) $TAG not okay!"
          exit 1
        fi

        if [[ "${VERSION}" =~ ^[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)?-latest.[0-9][0-9]*$ ]]; then
          echo version $VERSION okay
        else
          echo "version $VERSION not okay!"
          exit 1
        fi

        OLDBUILD=$(git show ${TAG}:.build.number | grep build.number | cut -f2 -d"=")
        if (( BUILD == OLDBUILD )); then
          echo "build.number $BUILD has not changed, please, update by running ant build locally!"
          exit 1
        fi

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Test with ant
      run: |
         ant -noinput -buildfile build.xml run_tests
         fails=$(grep -L  "Failures: 0, Errors: 0" test/junit/TEST-*)
         if [ -n "$fails" ]; then
           echo Errors in $fails
           cat $fails
           exit 1
         fi
      # do not exit before all commands are executed
      shell: bash --noprofile --norc -o pipefail {0}
      
    - name: Build with ant
      run: ant -noinput -buildfile build.xml

    - name: Read RELEASENOTES and CHANGELOG
      id: changelog
      run: |
        value=$(cat doc/NIGHTLY.txt | iconv -f ISO-8859-1; echo -e '\n\n'; echo -e '\n# Excerpt from CHANGELOG.txt\n\n'; head -20 CHANGELOG.txt | iconv -f ISO-8859-1; echo -e '\n...\n' )
        json_escape () {
          printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))[1:-1]'
        }
        value=$(json_escape "$value")
        echo "::set-env name=BODY::$value"

    - name: Publish git tag "vX.Y-latest"
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git remote -v
        git tag -f "${TAG}"
        REMOTE="https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
        git push --force "$REMOTE" "${TAG}"

    - name: Create release
      uses: meeDamian/github-release@2.0
      with:
        prerelease: true
        allow_override: true
        token: ${{ secrets.GITHUB_TOKEN }}
        commitish: master
        tag: ${{ env.TAG }}
        name: Pre-Release  v${{ env.VERSION }}
        body: ${{ env.BODY }}
        gzip: folders
        files: >
          LICENSE.txt
          README.md
          RELEASENOTES.txt
          CHANGELOG.txt
          magellan_v${{ env.VERSION }}.jar
          magellan_v${{ env.VERSION }}.zip

