name: Create versioned release
# Test, build, and publish a release draft on new vX.Y.Z tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create versioned release draft
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Generate version string
      id: get-version
      run: |
        BASE=$(ant -q -S print_version)
        echo "::set-env name=SHORT::$(echo "${BASE}" | cut -d. -f-2)"
        echo "::set-env name=VERSION::${BASE}"
        echo "::set-env name=TAG::v${VERSION}"

        REFTAG="$(echo "$GITHUB_REF" | awk -F/ '{print $NF}')"
        echo "::set-env name=REFTAG::$REFTAG"
        echo "::set-env name=REFSHORT::$(echo "${REFTAG#v}" | cut -d. -f-2)"
      
    - name: Sanity check
      run: |
        if [[ "$TAG" =~ ^v[0-9][0-9]*[.][0-9][0-9]*([.][0-9][0-9]*)?(-[a-z][a-z0-9]*([.][0-9])*)?$ ]]; then
          echo version $TAG okay
        else
          echo version $TAG not okay!
          exit 1
        fi

        if [[ "$TAG" == "$REFTAG" ]]; then
          echo tags match
        else
          echo $TAG != $REFTAG
          exit 1
        fi

    - name: Test with ant
      run: |
         ant -noinput -buildfile build.xml run_tests
         fails=$(grep -L  "Failures: 0, Errors: 0" test/junit/TEST-*)
         if [ -n "$fails" ]; then
           echo Errors in $fails
           cat $fails
           exit 1
         fi
      # do not exit before all commands are executed
      shell: bash --noprofile --norc -o pipefail {0}
      
    - name: Build with ant
      run: ant -noinput -buildfile build.xml

    - name: Read RELEASENOTES and CHANGELOG
      id: changelog
      run: |
        value=$(cat RELEASENOTES.txt | iconv -f ISO-8859-1)
        json_escape () {
          printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))[1:-1]'
        }
        value=$(json_escape "$value")
        echo "::set-env name=BODY::$value"

    - name: Create release
      uses: meeDamian/github-release@2.0
      with:
        draft: true
        prerelease: false
        allow_override: false
        token: ${{ secrets.GITHUB_TOKEN }}
        commitish: master
        tag: ${{ env.TAG }}
        name: Stable Release  ${{ env.VERSION }}
        body: ${{ env.BODY }}
        gzip: folders
        files: >
          LICENSE.txt
          README.md
          RELEASENOTES.txt
          CHANGELOG.txt
          magellan_v${{ env.BASE }}.jar
         magellan_v${{ env.BASE }}.zip

