name: Notify meta of published release
# react on published release: notify magellan-meta

on:
  release:
    types: [published]

jobs:
  trigger:
    name: trigger
    runs-on: ubuntu-latest

    steps:
    - name: set env
      run: |
        TAG="$(echo "${{ github.ref }}" | awk -F/ '{print $NF}')"
        echo "::set-env name=TAG::$TAG"

    - name: prepare
      run: |
        set -x
        if [[ "${{ env.TAG }}" =~ .*-[0-9.]*\([a-zA-Z][a-zA-Z]*\).* ]]; then
          TYPE=$(echo ${{ env.TAG }} | sed -e "s/.*-[0-9.]*\([a-zA-Z][a-zA-Z]*\).*/\1/")
        else
          TYPE=stable
        fi
        if [[ ! "$TYPE" =~ ^[a-zA-Z]+$ ]]; then
          echo "invalid type $TYPE"
          exit 1
        fi
        echo "::set-env name=TYPE::$TYPE"

    - name: trigger meta action
      run: |
        curl -X POST https://api.github.com/repos/${{ github.repository_owner }}/magellan-meta/dispatches \
          -H 'Accept: application/vnd.github.everst-preview+json' \
          -u magellan-meta-machineuser:${{ secrets.META_REPO_ACCESS }} \
          --data '{
            "event_type": "actions-release-trigger",
            "client_payload": {
              "ref" : "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "caller_repository" : "${{ github.repository }}",
              "meta_repository" : "${{ github.repository_owner }}/magellan-meta",
              "tag" : "${{ env.TAG }}",
              "type": "${{ env.TYPE }}" }}'

